/**
 * Русские имена персонажей (перекрывают nameRu в RAW).
 */
export const CHARACTER_NAME_RU = {
  gorou: 'Горо',
  'yae-miko': 'Яэ Мико',
  yoimiya: 'Ёимия',
  'kaedehara-kazuha': 'Кадзуха',
  'kuki-shinobu': 'Синобу',
  'raiden-shogun': 'Рейден',
  'kujou-sara': 'Сара',
  sayu: 'Саю',
  thoma: 'Тома',
  'shikanoin-heizou': 'Хейдзо',
  kirara: 'Кирара',
  'sangonomiya-kokomi': 'Кокоми',
  tighnari: 'Тигнари',
  collei: 'Коллеи',
  nilou: 'Нилоу',
  candace: 'Кандак',
  layla: 'Лайла',
  nahida: 'Нахида',
  wanderer: 'Бродяга',
  faruzan: 'Фарузан',
  sethos: 'Сефос',
  lyney: 'Лини',
  lynette: 'Линетт',
  freminet: 'Фремине',
  neuvillette: 'Нёвиллет',
  wriothesley: 'Ризли',
  furina: 'Фурина',
  charlotte: 'Шарлотта',
  navia: 'Навия',
  chevreuse: 'Шеврёз',
  clorinde: 'Клоринда',
  sigewinne: 'Сиджвин',
  emilie: 'Эмилия',
  escoffier: 'Эскофье',
  mualani: 'Муалани',
  kachina: 'Качина',
  kinich: 'Кинич',
  xilonen: 'Шилонен',
  chasca: 'Часка',
  mavuika: 'Мавуика',
  citlali: 'Ситлали',
  iansan: 'Иансан',
  ineffa: 'Инеффа',
  lauma: 'Лаума',
  aino: 'Айно',
  nefer: 'Нефер',
  columbina: 'Колумбина',
  illuga: 'Иллуга',
  linnea: 'Линнея',
  tartaglia: 'Тарталья',
  arlecchino: 'Арлекино',
  xianyun: 'СяньЮнь',
};
